@echo off
REM HomeworldSDL — generated by setup.ps1 / updated Phase 11
set HW_Data=D:\Projects\Homeworld\assets
set HW_Bridge_State=D:\Projects\Homeworld\mothership\state
REM Add MSYS2 MinGW64 to PATH so SDL2.dll and other runtime DLLs are found
set PATH=C:\msys64\mingw64\bin;%PATH%
if not exist "D:\Projects\Homeworld\HomeworldSDL\build\homeworld.exe" ( echo Binary not found. Re-run setup.ps1. & pause & exit /b 1 )
if not exist "%HW_Data%\homeworld.big" ( echo Assets not found in %HW_Data%. Run stage-assets.ps1. & pause & exit /b 1 )
echo Starting HomeworldSDL  [Data: %HW_Data%]  [Bridge: %HW_Bridge_State%]
cd /d "D:\Projects\Homeworld\HomeworldSDL\build"
homeworld.exe -d "%HW_Data%" %*
if errorlevel 1 ( echo. & echo Exited with error. Try launch-windowed.bat & pause )
