@echo off
REM HomeworldSDL ? generated by setup.ps1
set HW_Data=D:\Projects\Homeworld\assets
if not exist "D:\Projects\Homeworld\HomeworldSDL\build\homeworld.exe" ( echo Binary not found. Re-run setup.ps1. & pause & exit /b 1 )
if not exist "%HW_Data%\homeworld.big" ( echo Assets not found in %HW_Data%. Run stage-assets.ps1. & pause & exit /b 1 )
echo Starting HomeworldSDL  [Data: %HW_Data%]
"D:\Projects\Homeworld\HomeworldSDL\build\homeworld.exe" %*
if errorlevel 1 ( echo. & echo Exited with error. Try launch-windowed.bat & pause )
